#!/usr/bin/env bash
#
# Refreshes QDEF-SPEC-cached.md from the live upstream QDEF spec
# (qdef-format/qdef-format.github.io, docs/QDEF-SPEC.md on the main
# branch -- the project moved here from mofosyne/qdef; see CLAUDE.md).
# This cached copy
# is what app/build.gradle's copyQdefSpecToRawRes task bundles into the
# in-app "Wire Format Spec" viewer (SpecActivity) for offline reading --
# QDEF-SPEC.md itself stays a short pointer (see its own header) so anyone
# reading this repo on GitHub always gets sent to the real, current spec
# instead of a copy that can silently drift.
#
# This script replaces the old habit of hand-copy-pasting the upstream
# spec into this repo on an ad hoc basis (see SPEC.md's version history /
# CLAUDE.md for that history) -- run it, review the diff, commit if it
# looks right. Not wired into CI or any build step; deliberately manual,
# so a bad upstream fetch or an unreviewed upstream change never lands
# silently.
#
# Requires: curl. Run from anywhere; it cds to the repo root itself.
#
# Usage:
#   scripts/sync-qdef-spec.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE_FILE="$REPO_ROOT/QDEF-SPEC-cached.md"
SOURCE_URL="https://raw.githubusercontent.com/qdef-format/qdef-format.github.io/main/docs/QDEF-SPEC.md"

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

echo "Fetching $SOURCE_URL ..."
if ! curl -fsSL "$SOURCE_URL" -o "$TMP_FILE"; then
    echo "error: fetch failed -- upstream unreachable, moved, or renamed the file." >&2
    echo "       Not touching $CACHE_FILE." >&2
    exit 1
fi

if [ ! -s "$TMP_FILE" ]; then
    echo "error: fetched file is empty -- refusing to overwrite $CACHE_FILE." >&2
    exit 1
fi

{
    echo "<!--"
    echo "AUTO-GENERATED by scripts/sync-qdef-spec.sh -- do not hand-edit."
    echo "Mirrors $SOURCE_URL (main branch). Re-run the script to refresh;"
    echo "changes made directly to this file will be overwritten next sync."
    echo "-->"
    echo
    cat "$TMP_FILE"
} > "$CACHE_FILE"

echo "Wrote $CACHE_FILE"
if command -v git >/dev/null 2>&1 && git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    if ! git -C "$REPO_ROOT" ls-files --error-unmatch QDEF-SPEC-cached.md >/dev/null 2>&1; then
        echo "New file (not yet tracked by git) -- review it, then git add + commit."
    elif git -C "$REPO_ROOT" diff --quiet -- QDEF-SPEC-cached.md 2>/dev/null; then
        echo "No changes -- already up to date."
    else
        echo
        echo "Diff against the committed copy:"
        git -C "$REPO_ROOT" --no-pager diff -- QDEF-SPEC-cached.md || true
        echo
        echo "Review the diff above, then commit QDEF-SPEC-cached.md if it looks right."
    fi
fi
